### PR TITLE
Fixes support for LLVM 10 and 11

### LINKED ISSUE #75: Build error using llvm 10 on mac
During the build of rellic I get a number of compilation errors:
`[ 19%] Building CXX object rellic/CMakeFiles/rellic.dir/AST/Compat/Stmt.cpp.o
[ 19%] Building CXX object rellic/CMakeFiles/rellic.dir/AST/Compat/Expr.cpp.o
[ 23%] Building CXX object rellic/CMakeFiles/rellic.dir/AST/InferenceRule.cpp.o
[ 26%] Building CXX object rellic/CMakeFiles/rellic.dir/AST/CXXToCDecl.cpp.o
[ 30%] Building CXX object rellic/CMakeFiles/rellic.dir/AST/DeadStmtElim.cpp.o
[ 34%] Building CXX object rellic/CMakeFiles/rellic.dir/AST/CondBasedRefine.cpp.o
[ 38%] Building CXX object rellic/CMakeFiles/rellic.dir/AST/ExprCombine.cpp.o
[ 42%] Building CXX object rellic/CMakeFiles/rellic.dir/AST/GenerateAST.cpp.o
[ 46%] Building CXX object rellic/CMakeFiles/rellic.dir/AST/IRToASTVisitor.cpp.o
[ 50%] Building CXX object rellic/CMakeFiles/rellic.dir/AST/LoopRefine.cpp.o
/Users/brianmosher/Documents/repos/rellic/rellic/AST/IRToASTVisitor.cpp:87:57: error: too few arguments to function
      call, expected 5, have 4
          clang::ArrayType::ArraySizeModifier::Normal, 0);
                                                        ^
/usr/local/share/trailofbits/libraries/llvm/include/clang/AST/ASTContext.h:1349:3: note: 'getConstantArrayType' declared
      here
  QualType getConstantArrayType(QualType EltTy, const llvm::APInt &ArySize,
  ^
In file included from /Users/brianmosher/Documents/repos/rellic/rellic/AST/ExprCombine.cpp:20:
/Users/brianmosher/Documents/repos/rellic/rellic/AST/ExprCombine.h:27:34: error: expected class name
class ExprCombine : public llvm::ModulePass, `

Examining the caller and the ASTContext.h header, there does seem to be a mismatch in the number of args and expected parameters.

rellic/rellic/AST/IRToASTVisitor.cpp:
`    case llvm::Type::ArrayTyID: {
      auto arr = llvm::cast<llvm::ArrayType>(type);
      auto elm = GetQualType(arr->getElementType());
      result = ast_ctx.getConstantArrayType(
          elm, llvm::APInt(32, arr->getNumElements()),
          clang::ArrayType::ArraySizeModifier::Normal, 0);
    } break;
`
libraries/llvm/include/clang/AST/ASTContext.h:
`  QualType getConstantArrayType(QualType EltTy, const llvm::APInt &ArySize,
                                const Expr *SizeExpr,
                                ArrayType::ArraySizeModifier ASM,
                                unsigned IndexTypeQuals) const;
`
This is with llvm-10 installed using pkgman.py from cxxx-common.

### PR DESCRIPTION
**Pull request by surovic**
resolves #75

### CODE REVIEW

File: rellic/AST/Compat/Mangle.h [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+#pragma once
+
+#include <clang/AST/Mangle.h>
+
```
Comment (pgoodman) [inline rellic/AST/Compat/Mangle.h:20]: Can you forward declare `clang::MangleContext` and the other classes, then remove the include of the mangle.h?

**Review by pgoodman — CHANGES_REQUESTED** [review]

File: rellic/AST/Compat/Mangle.h (hunk 1 above)
Comment (surovic) [reply rellic/AST/Compat/Mangle.h:28]: Done.

**Review by pgoodman — APPROVED** [review]
