### PR TITLE
Fixes #261

### LINKED ISSUE #261: Probable bug in `LoopRefine`
I suspect `LoopRefine` contains a bug. I cannot give a specific repro case, but when trying to improve condition propagation I ran into an issue with loops with this form:
```
while(1U) {
  a = sth;
  if(a == 10) {
    break;
  }
  if(a != 10) {
    body;
  }
}
```
getting turned into
```
do {
  a = sth;
  body;
} while(a != 10);
```
which is incorrect because the guard is not checked after `a = sth;`.

### PR DESCRIPTION
**Pull request by frabert**
Also improves the amount of propagated conditions by `NestedCondProp`

### CODE REVIEW

**Review by pgoodman — APPROVED** [review]

File: lib/AST/Util.cpp [hunk 1]
```diff
@@ -316,6 +316,26 @@ clang::Expr *Clone(clang::ASTUnit &unit, clang::Expr *expr,
   return CHECK_NOTNULL(cloner.Visit(CHECK_NOTNULL(expr)));
 }
 
+static clang::Expr *StripParens(clang::Expr *expr) {
```
Comment (surovic) [inline lib/AST/Util.cpp:319]: Can this be replaced by `clang::Expr::IgnoreParens()` ?

File: lib/AST/Util.cpp [hunk 2]
```diff
@@ -316,6 +316,26 @@ clang::Expr *Clone(clang::ASTUnit &unit, clang::Expr *expr,
...
+static clang::Expr *ApplyLNot(rellic::ASTBuilder &ast, clang::Expr *expr) {
+  if (auto unop = clang::dyn_cast<clang::UnaryOperator>(expr)) {
+    if (unop->getOpcode() == clang::UO_LNot) {
+      return unop->getSubExpr();
+    }
+  }
+  return ast.CreateLNot(expr);
+}
+
+clang::Expr *Negate(rellic::ASTBuilder &ast, clang::Expr *expr) {
```
Comment (surovic) [inline lib/AST/Util.cpp:335]: Do we really need to do this outside of `ExprCombine` ? There should be rewriting rules for this already, right?

File: lib/AST/LoopRefine.cpp [hunk 3]
```diff
@@ -100,10 +100,12 @@ class DoWhileRule : public InferenceRule {
...
                                         comp->body_end() - 1);
+    ASTBuilder ast(unit);
     if (auto else_stmt = ifstmt->getElse()) {
-      new_body.push_back(else_stmt);
+      auto cond_inv{ast.CreateLNot(cond)};
+      CopyProvenance(cond, cond_inv, provenance.use_provenance);
+      new_body.push_back(ast.CreateIf(cond_inv, else_stmt));
     }
-    ASTBuilder ast(unit);
     auto cond_inv{ast.CreateLNot(cond)};
```
Comment (surovic) [inline lib/AST/LoopRefine.cpp:109]: Am I right that we have `auto cond_inv{ast.CreateLNot(cond)}` twice here because of provenance tracking?

File: lib/AST/LoopRefine.cpp [hunk 4]
```diff
@@ -147,11 +149,13 @@ class NestedDoWhileRule : public InferenceRule {
...
+    ASTBuilder ast(unit);
     if (auto else_stmt = cond->getElse()) {
-      do_body.push_back(else_stmt);
+      auto cond_inv{ast.CreateLNot(cond->getCond())};
+      CopyProvenance(cond->getCond(), cond_inv, provenance.use_provenance);
+      do_body.push_back(ast.CreateIf(cond_inv, else_stmt));
     }
 
-    ASTBuilder ast(unit);
     auto do_cond{ast.CreateLNot(cond->getCond())};
```
Comment (surovic) [inline lib/AST/LoopRefine.cpp:159]: Same as `cond_inv` above.

**Review by surovic — CHANGES_REQUESTED** [review]

File: lib/AST/Util.cpp (hunk 2 above)
Comment (frabert) [reply lib/AST/Util.cpp:335]: Since we changed the replacement mechanism in `NCP` to be syntactical, in this situation
```
if(!(a == b)) {
  ...
} else {
  if(a == b) {
    ...
  }
}
```
the condition would not be propagated to the `else` branch. The conditions need to be stripped down to the "bare minimum"

File: lib/AST/Util.cpp (hunk 1 above)
Comment (frabert) [reply lib/AST/Util.cpp]: Done!

File: lib/AST/Util.cpp (hunk 2 above)
Comment (surovic) [reply lib/AST/Util.cpp:328]: Got it!

**Review by surovic — APPROVED** [review]
